### ISSUE TITLE
Regarding the records from 07.05 Web Prog with Java

### ISSUE THREAD

**Issue by vitaliistankov** [nshopova/spring-mvc-demo#1]
Добър ден!

Писах ви на имейла и дублирам тука
Ще ви помоля да ми изпратите и връзки към записите на лекция от 07.05 на vitalii.stankov@gmail.com 
Много ви благодаря за хубаво обяснение на материала за Spring. Тези неща, които бяха трудни за разбиране за мен, сега станаха много по-ясни. 
Поздрави!
Виталий

**Comment by nshopova** [comment]
Здравейте, 
Изпратих Ви линковете към записте на имейла. Радвам се, че е имало полза от презентациите. За мен това бяха първите лекции, които водя, и ще оценя всякаква обратна връзка (особено критична такава) - от Вас и Вашите колеги.

Хубав ден!
Николина

**Comment by vitaliistankov** [comment]
Благодаря!
